import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div
          className=" px-40 mx-auto p-4 min-h-screen "
          style={{ backgroundImage: "url('/nav.jpg')" }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
